services:
  - type: web
    name: job365-django
    env: python
    buildCommand: |
      pip install -r requirements.txt
      npm install
      npm run build
      python manage.py collectstatic --noinput
    startCommand: gunicorn Jobs.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Jobs.settings
      - key: PYTHON_VERSION
        value: 3.11
