# Generated by Django 5.1.7 on 2025-04-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('urgent', models.BooleanField(default=False)),
            ],
        ),
    ]
