# Generated by Django 5.1.7 on 2025-04-01 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_type',
            new_name='hourly_rates',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='job_details',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='job_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='urgent',
        ),
        migrations.AddField(
            model_name='job',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancies',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
