# Generated by Django 5.1.7 on 2025-04-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_adminjobapplication_delete_applicationdisplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
