# Generated by Django 5.1.7 on 2025-04-09 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_job_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminjobapplication',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='adminjobapplication',
            name='job_name',
        ),
        migrations.AddField(
            model_name='adminjobapplication',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admin_panel.job'),
            preserve_default=False,
        ),
    ]
