# Generated by Django 5.1.7 on 2025-05-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_adminjobapplication_age_adminjobapplication_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminjobapplication',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
