# Generated by Django 5.1.7 on 2025-04-02 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_job_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='job_details',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.AddField(
            model_name='job',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.CharField(default='600', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='job',
            name='hourly_rates',
            field=models.CharField(default='600', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_name',
            field=models.CharField(default='6 months', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='vacancies',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
