# Generated by Django 5.1.7 on 2025-04-05 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_job_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('place', models.CharField(max_length=200)),
                ('school1_name', models.CharField(blank=True, max_length=200)),
                ('school1_place', models.CharField(blank=True, max_length=200)),
                ('school1_marks', models.CharField(blank=True, max_length=50)),
                ('school1_certificate', models.FileField(blank=True, upload_to='certificates/')),
                ('school2_name', models.CharField(blank=True, max_length=200)),
                ('school2_place', models.CharField(blank=True, max_length=200)),
                ('school2_marks', models.CharField(blank=True, max_length=50)),
                ('school2_certificate', models.FileField(blank=True, upload_to='certificates/')),
                ('college_name', models.CharField(blank=True, max_length=200)),
                ('college_place', models.CharField(blank=True, max_length=200)),
                ('college_marks', models.CharField(blank=True, max_length=50)),
                ('college_certificate', models.FileField(blank=True, upload_to='certificates/')),
                ('skills', models.CharField(max_length=300)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile_photos/')),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
