# Generated by Django 5.1.7 on 2025-04-07 14:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_applicationdisplay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FullJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('place', models.CharField(max_length=200)),
                ('school1_name', models.CharField(blank=True, max_length=200)),
                ('school1_place', models.CharField(blank=True, max_length=200)),
                ('school1_marks', models.CharField(blank=True, max_length=50)),
                ('school1_certificate', models.FileField(blank=True, upload_to='certificates/')),
                ('school2_name', models.CharField(blank=True, max_length=200)),
                ('school2_place', models.CharField(blank=True, max_length=200)),
                ('school2_marks', models.CharField(blank=True, max_length=50)),
                ('school2_certificate', models.FileField(blank=True, upload_to='certificates/')),
                ('college_name', models.CharField(blank=True, max_length=200)),
                ('college_place', models.CharField(blank=True, max_length=200)),
                ('college_marks', models.CharField(blank=True, max_length=50)),
                ('college_certificate', models.FileField(blank=True, upload_to='certificates/')),
                ('skills', models.CharField(max_length=300)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile_photos/')),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationdisplay',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobalert',
            name='jobseeker',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='job',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='jobseeker',
        ),
        migrations.DeleteModel(
            name='SiteAnalytics',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applied_at',
            new_name='applied_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='age',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='college_certificate',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='college_marks',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='college_place',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='place',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='school1_certificate',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='school1_marks',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='school1_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='school1_place',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='school2_certificate',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='school2_marks',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='school2_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='school2_place',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='skills',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='company_name',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_name',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.DeleteModel(
            name='Applicationdisplay',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='JobAlert',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='SavedJob',
        ),
    ]
