# Generated by Django 5.1.7 on 2025-04-09 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_siteanalytics_subscriptionplan_jobapplication_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='age',
            field=models.PositiveIntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='dob',
            field=models.DateField(default='2000-01-01'),

            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='full_name',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='gender',
            field=models.CharField(default=23, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='App.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='place',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skills',
            field=models.TextField(default=23),
            preserve_default=False,
        ),
    ]
