# Generated by Django 5.1.7 on 2025-05-26 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_job_user'),
        ('admin_panel', '0010_alter_adminjobapplication_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.job'),
        ),
    ]
