# Generated by Django 5.1.7 on 2025-06-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_jobapplication_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
