# Generated by Django 5.1.7 on 2025-06-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
